config/routes.rb
Rails.application.routes.draw do
  
  resources :variances do
    collection do
      post :import
      delete :cleardata
    end
  end
      
  resources :locations do
    collection do
      post :import
      delete :cleardata
      post :businessunit
    end
  end
  
  match '/business-form', to: 'home#business_form', via: [:get, :post]

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#home'
  resources :masters do
    collection do
      post :import
      delete :cleardata
      get :search
      get :prepare_import
    end  
  end
  
  namespace :api do
    resources :files, only: %i(index) do
      collection do
        get :download_db
        post :upload_csv
        get :verify_upload
      end
    end
  end

end

app/models/master.rb
class Master < ApplicationRecord
    require 'CSV'
    def self.import(file)
        data = []
        filename = File.basename(file)

        if filename.present?
          where(filename: filename).destroy_all
        end

        CSV.open(file, headers: :first_row).map do |rows|
            row = {filename: filename}
            barcodes = []
            rows.each do |f,v|
                if f.to_s.match(/Barcode\d{1,}/) 
                    barcodes.push(v) if v.present?
                else
                    row[f] = v
                end
            end
            row.merge!(created_at: DateTime.now, updated_at: DateTime.now)
            barcodes.each do |barcode|
                data.push(row.merge(BarcodeSBC: barcode))
            end
            if barcodes.blank?
                row[:BarcodeSBC] = row["BarcodeIBC"]
                data.push(row)
            end
        end
        Master.insert_all!(data)
    end

    def self.search(params)
        masters = Master.where("SKU LIKE ?", "%#{params[:search]}%") if params[:search].present?
        return masters
    end 
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_master, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :prepare_import 

  # GET /masters
  # GET /masters.json
  def index
    @masters = Master.all.paginate(page: params[:page], per_page: 200)
  end

  # GET /masters/1
  # GET /masters/1.json
  def show
  end

  # GET /masters/new
  def new
    @master = Master.new
  end

  # GET /masters/1/edit
  def edit
  end

  def search 
    if params[:search].blank?
      @masters = Master.all.paginate(page: params[:page], per_page: 200)
    else
      @masters = Master.search(params)
    end
  end  

  # POST /masters
  # POST /masters.json
  def create
    @master = Master.new(master_params)

    respond_to do |format|
      if @master.save
        format.html { redirect_to @master, notice: 'Master was successfully created.' }
        format.json { render :show, status: :created, location: @master }
      else
        format.html { render :new }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masters/1
  # PATCH/PUT /masters/1.json
  def update
    respond_to do |format|
      if @master.update(master_params)
        format.html { redirect_to @master, notice: 'Master was successfully updated.' }
        format.json { render :show, status: :ok, location: @master }
      else
        format.html { render :edit }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1
  # DELETE /masters/1.json
  def destroy
    @master.destroy
    respond_to do |format|
      format.html { redirect_to masters_url, notice: 'Master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    if params[:name].present? && params[:unit].present?
      MasterBusiness.create_or_update({
        name: params[:name], 
        unit: params[:unit], 
        user_id: current_user.id, 
        filename: File.basename(params[:file])
      })
    end

    Master.import(params[:file])
    redirect_to masters_path, notice: "Master data added successfully !!"
  end 


  def cleardata
    # ActiveRecord::Base.connection.execute("DELETE FROM masters")
    Master.connection.truncate(Master.table_name)
    redirect_to masters_path
  end 

  def prepare_import
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master
      @master = Master.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def master_params
      params.require(:master).permit(:CountName, :StoreCode, :StoreName, :VenderCode, :VenderName, :DeptCode, :DeptName, :SubDeptCode, :SubDeptName, :Class, :ClassName, :SubClass, :SubClassName, :SKUType, :SpecialAttribute, :SKU, :BarcodeIBC, :BarcodeSBC, :Barcode1, :Barcode2, :Barcode3, :Barcode4, :Barcode5, :Barcode6, :Barcode7, :Barcode8, :Barcode9, :Barcode10, :ProductName, :Brand, :Model, :UnitOfMeasure, :Stock, :PackSize, :Cost, :RetailPrice, :Status)
    end
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/views/masters/_form.html.erb
<%= form_with(model: master, local: true) do |form| %>
  <% if master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(master.errors.count, "error") %> prohibited this master from being saved:</h2>

      <ul>
        <% master.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="margin-top: 30px">
  <div class="card">
  <div class="card-body">

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :CountName, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :CountName, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :StoreCode, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :StoreCode, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :StoreName, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :StoreName, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :VenderCode, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.number_field :VenderCode, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :VenderName, class: "col-form-label" %></h4></div><br /> 
    <div class="col-sm-10"><h4><%= form.text_field :VenderName, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :DeptCode, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.number_field :DeptCode, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :DeptName, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :DeptName, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :SubDeptCode, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.number_field :SubDeptCode, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :SubDeptName, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :SubDeptName, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :Class, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.number_field :Class, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :ClassName, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :ClassName, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :SubClass, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.number_field :SubClass, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :SubClassName, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :SubClassName, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :SKUType, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :SKUType, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :SpecialAttribute, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :SpecialAttribute, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :SKU, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :SKU, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :BarcodeIBC, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :BarcodeIBC, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :BarcodeSBC, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :BarcodeSBC, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :ProductName, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :ProductName, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :Brand, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :Brand, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"><h4><%= form.label :Model, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :Model, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :UnitOfMeasure, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :UnitOfMeasure, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :Stock, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :Stock, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :PackSize, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :PackSize, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :Cost, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :Cost, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :RetailPrice, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :RetailPrice, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :Status, class: "col-form-label"%></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :Status, class: "form-control" %></h4></div>
  </div>

  <div class="actions", class: 'btn btn-mini btn-success'>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/masters/_import_form.html.erb
<div class="card" style="margin:10px;border: 1px solid;padding:10px;width:50%">
 <div class="card-header bg-success"><h4 style="padding:10px">Setup Page</h4></div>
   <div class="card-body">

    <%= form_tag(import_masters_path, method: :post, multipart: true) do  %>
      <div class="form-group row">
        <div class="col-sm-2 col-form-label">Business Name</div><br />
        <div class="col-sm-10"><%= text_field_tag :name, master_business&.business_name, class: "form-control", required: true%></div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2 col-form-label">Business Unit</div><br />
        <div class="col-sm-10"><%= text_field_tag :unit, master_business&.business_unit, class: "form-control", required: true%></div>
      </div>

      <div class="actions">
        <%= file_field_tag :file, style: 'display:inline-block', required: true %> <%= submit_tag "Import Data" , class: "btn btn-success", style: 'display:inline-block' %> <br />
      </div>
    <% end %>
  </div>
</div>

app/views/masters/edit.html.erb
<h1>Editing Master</h1>

<%= render 'form', master: @master %>

<%= link_to 'Show', @master , class: 'btn btn-mini btn-success'%> |
<%= link_to 'Back', masters_path,class: 'btn btn-mini btn-warning' %>

app/views/masters/index.html.erb
<h2>Import master data </h2>
<%= link_to 'IMPORT MASTER DATA', prepare_import_masters_path, remote: true, class: 'btn btn-mini btn-warning' %> | 
<%= link_to "CLEAR MASTER DATA", cleardata_masters_path, :method => :delete, class: 'btn btn-mini btn-danger' %> |
<%= link_to 'ADD NEW RECORD', new_master_path, class: 'btn btn-mini btn-success' %>

<div id="import-form"></div>

<h3> <%= @masters.count %> records imported successfully</h3>

<%= form_tag(search_masters_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %> 

<h1>Master Data</h1>

<div class="media">
<div class="media-body">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>CountName</th>
      <th>StoreCode</th>
      <th>StoreName</th>
      <th>VenderCode</th>
      <th>VenderName</th>
      <th>DeptCode</th>
      <th>DeptName</th>
      <th>SubDeptCode</th>
      <th>SubDeptName</th>
      <th>Class</th>
      <th>ClassName</th>
      <th>SubClass</th>
      <th>SubClassName</th>
      <th>SKUType</th>
      <th>SpecialAttribute</th>
      <th>SKU</th>
      <th>BarcodeIBC</th>
      <th>BarcodeSBC</th>
      <th>ProductName</th>
      <th>Brand</th>
      <th>Model</th>
      <th>UnitOfMeasure</th>
      <th>Stock</th>
      <th>Pack Size</th>
      <th>Cost</th>
      <th>Retail price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @masters.each do |master| %>
      <tr>
        <td><%= master.CountName %></td>
        <td><%= master.StoreCode %></td>
        <td><%= master.StoreName %></td>
        <td><%= master.VenderCode %></td>
        <td><%= master.VenderName %></td>
        <td><%= master.DeptCode %></td>
        <td><%= master.DeptName %></td>
        <td><%= master.SubDeptCode %></td>
        <td><%= master.SubDeptName %></td>
        <td><%= master.Class %></td>
        <td><%= master.ClassName %></td>
        <td><%= master.SubClass %></td>
        <td><%= master.SubClassName %></td>
        <td><%= master.SKUType %></td>
        <td><%= master.SpecialAttribute %></td>
        <td><%= master.SKU %></td>
        <td><%= master.BarcodeIBC %></td>
        <td><%= master.BarcodeSBC %></td>
        <td><%= master.ProductName %></td>
        <td><%= master.Brand %></td>
        <td><%= master.Model %></td>
        <td><%= master.UnitOfMeasure %></td>
        <td><%= master.Stock %></td>
        <td><%= master.PackSize %></td>
        <td><%= master.Cost %></td>
        <td><%= master.RetailPrice %></td>
        <td><%= master.Status %></td>
        <td><%= link_to 'Show', master, class: 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'Edit', edit_master_path(master), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', master, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>

<%= will_paginate @masters, renderer: BootstrapPagination::Rails  %>

app/views/masters/new.html.erb
<h1>New Master</h1>

<%= render 'form', master: @master %>

<%= link_to 'Back', masters_path , class: 'btn btn-mini btn-warning'%>

app/views/masters/prepare_import.js.erb
(function(w,d){
  d.getElementById("import-form").innerHTML = "<%= j render(partial: 'import_form') %>";
})(window,document)

app/views/masters/search.html.erb
<h2>Search Results </h2>

<div class="media">
<div class="media-body">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>CountName</th>
      <th>StoreCode</th>
      <th>StoreName</th>
      <th>VenderCode</th>
      <th>VenderName</th>
      <th>DeptCode</th>
      <th>DeptName</th>
      <th>SubDeptCode</th>
      <th>SubDeptName</th>
      <th>Class</th>
      <th>ClassName</th>
      <th>SubClass</th>
      <th>SubClassName</th>
      <th>SKUType</th>
      <th>SpecialAttribute</th>
      <th>SKU</th>
      <th>BarcodeIBC</th>
      <th>BarcodeSBC</th>
      <th>ProductName</th>
      <th>Brand</th>
      <th>Model</th>
      <th>UnitOfMeasure</th>
      <th>Stock</th>
      <th>Pack Size</th>
      <th>Cost</th>
      <th>Retail price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @masters.each do |master| %>
      <tr>
        <td><%= master.CountName %></td>
        <td><%= master.StoreCode %></td>
        <td><%= master.StoreName %></td>
        <td><%= master.VenderCode %></td>
        <td><%= master.VenderName %></td>
        <td><%= master.DeptCode %></td>
        <td><%= master.DeptName %></td>
        <td><%= master.SubDeptCode %></td>
        <td><%= master.SubDeptName %></td>
        <td><%= master.Class %></td>
        <td><%= master.ClassName %></td>
        <td><%= master.SubClass %></td>
        <td><%= master.SubClassName %></td>
        <td><%= master.SKUType %></td>
        <td><%= master.SpecialAttribute %></td>
        <td><%= master.SKU %></td>
        <td><%= master.BarcodeIBC %></td>
        <td><%= master.BarcodeSBC %></td>
        <td><%= master.ProductName %></td>
        <td><%= master.Brand %></td>
        <td><%= master.Model %></td>
        <td><%= master.UnitOfMeasure %></td>
        <td><%= master.Stock %></td>
        <td><%= master.PackSize %></td>
        <td><%= master.Cost %></td>
        <td><%= master.RetailPrice %></td>
        <td><%= master.Status %></td>
        <td><%= link_to 'Show', master %></td>
        <td><%= link_to 'Edit', edit_master_path(master) %></td>
        <td><%= link_to 'Destroy', master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<p>
  <%= link_to 'Back to all master data', masters_path, class: 'btn btn-mini btn-warning' %>
</p>

<br>

app/views/masters/show.html.erb
<div class="container" style="margin-top: 30px">
<div class="card">
<div class="card-header bg-success"><h2>Item details</h2></div>
<div class="card-body">
<p id="notice"><%= notice %></p>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Countname:</h4></div>
<div class="col-sm-10"><h4><%= @master.CountName %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Storecode:</h4></div>
<div class="col-sm-10"><h4><%= @master.StoreCode %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Storename:</h4></div>
<div class="col-sm-10"><h4><%= @master.StoreName %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Vendercode:</h4></div>
<div class="col-sm-10"><h4><%= @master.VenderCode %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Vendername:</h4></div>
<div class="col-sm-10"><h4><%= @master.VenderName %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Deptcode:</h4></div>
<div class="col-sm-10"><h4><%= @master.DeptCode %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Deptname:</h4></div>
<div class="col-sm-10"><h4><%= @master.DeptName %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Subdeptcode:</h4></div>
<div class="col-sm-10"><h4><%= @master.SubDeptCode %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Subdeptname:</h4></div>
<div class="col-sm-10"><h4><%= @master.SubDeptName %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Class:</h4></div>
<div class="col-sm-10"><h4><%= @master.Class %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Classname:</h4></div>
<div class="col-sm-10"><h4><%= @master.ClassName %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Subclass:</h4></div>
<div class="col-sm-10"><h4><%= @master.SubClass %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Subclassname:</h4></div>
<div class="col-sm-10"><h4><%= @master.SubClassName %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Skutype:</h4></div>
<div class="col-sm-10"><h4><%= @master.SKUType %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Specialattribute:</h4></div>
<div class="col-sm-10"><h4><%= @master.SpecialAttribute %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Sku:</h4></div>
<div class="col-sm-10"><h4><%= @master.SKU %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Barcodeibc:</h4></div>
<div class="col-sm-10"><h4><%= @master.BarcodeIBC %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>BarcodeSBC:</h4></div>
<div class="col-sm-10"><h4><%= @master.BarcodeSBC %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Productname:</h4></div>
<div class="col-sm-10"><h4><%= @master.ProductName %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Brand:</h4></div>
<div class="col-sm-10"><h4><%= @master.Brand %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Model:</h4></div>
<div class="col-sm-10"><h4><%= @master.Model %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Unitofmeasure:</h4></div>
<div class="col-sm-10"><h4><%= @master.UnitOfMeasure %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Stock:</h4></div>
<div class="col-sm-10"><h4><%= @master.Stock %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Packsize:</h4></div>
<div class="col-sm-10"><h4><%= @master.PackSize %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Cost:</h4></div>
<div class="col-sm-10"><h4><%= @master.Cost %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Retailprice:</h4></div>
<div class="col-sm-10"><h4><%= @master.RetailPrice %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Status:</h4></div>
<div class="col-sm-10"><h4><%= @master.Status %></h4></div>
</div>

<%= link_to 'Edit', edit_master_path(@master), class: 'btn btn-mini btn-success' %> |
<%= link_to 'Back', masters_path , class: 'btn btn-mini btn-warning'%>