config/routes.rb
Rails.application.routes.draw do
  
  resources :variances do
    collection do
      post :import
      delete :cleardata
    end
  end
      
  resources :locations do
    collection do
      post :import
      delete :cleardata
      post :businessunit
    end
  end
  
  match '/business-form', to: 'home#business_form', via: [:get, :post]

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#home'
  resources :masters do
    collection do
      post :import
      delete :cleardata
      get :search
      get :prepare_import
    end  
  end
  
  namespace :api do
    resources :files, only: %i(index) do
      collection do
        get :download_db
        post :upload_csv
        get :verify_upload
      end
    end
  end

end

app/models/variance.rb
class Variance < ApplicationRecord
    require 'CSV'
    def self.import(file)
        h = CSV.open(file, headers: :first_row).map do |row| 
            row.to_h.merge!(created_at: DateTime.now, updated_at: DateTime.now)
        end
        Variance.insert_all!(h)
    end
end

app/controllers/variances_controller.rb
class VariancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variance, only: [:show, :edit, :update, :destroy]

  # GET /variances
  # GET /variances.json
  def index
    @variances = Variance.all.paginate(page: params[:page], per_page: 100)
  end

  # GET /variances/1
  # GET /variances/1.json
  def show
  end

  # GET /variances/new
  def new
    @variance = Variance.new
  end

  # GET /variances/1/edit
  def edit
  end

  # POST /variances
  # POST /variances.json
  def create
    @variance = Variance.new(variance_params)

    respond_to do |format|
      if @variance.save
        format.html { redirect_to @variance, notice: 'Variance was successfully created.' }
        format.json { render :show, status: :created, location: @variance }
      else
        format.html { render :new }
        format.json { render json: @variance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variances/1
  # PATCH/PUT /variances/1.json
  def update
    respond_to do |format|
      if @variance.update(variance_params)
        format.html { redirect_to @variance, notice: 'Variance was successfully updated.' }
        format.json { render :show, status: :ok, location: @variance }
      else
        format.html { render :edit }
        format.json { render json: @variance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variances/1
  # DELETE /variances/1.json
  def destroy
    @variance.destroy
    respond_to do |format|
      format.html { redirect_to variances_url, notice: 'Variance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Variance.import(params[:file])
    redirect_to variances_path, notice: "Variance data added successfully !!"
  end 

  def cleardata
    # ActiveRecord::Base.connection.execute("DELETE FROM masters")
    Variance.connection.truncate(Variance.table_name)
    redirect_to variances_path
  end 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variance
      @variance = Variance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def variance_params
      params.require(:variance).permit(:BARCODE, :LOCATION, :QUANTITY)
    end
end

app/helpers/variances_helper.rb
module VariancesHelper
end

app/views/variances/_form.html.erb
<%= form_with(model: variance, local: true) do |form| %>
  <% if variance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variance.errors.count, "error") %> prohibited this variance from being saved:</h2>

      <ul>
        <% variance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="margin-top: 30px">
  <div class="card">
  <div class="card-body">


  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :BARCODE, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :BARCODE , class: "form-control"%></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :LOCATION, class: "col-form-label" %></h4> </div><br />
  <div class="col-sm-10"><h4><%= form.text_field :LOCATION , class: "form-control"%></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :QUANTITY, class: "col-form-label" %></h4> </div><br />
  <div class="col-sm-10"><h4><%= form.text_field :QUANTITY, class: "form-control" %></h4></div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/variances/edit.html.erb
<h1>Editing Variance</h1>

<%= render 'form', variance: @variance %>

<%= link_to 'Show', @variance , class: 'btn btn-mini btn-success'%> |
<%= link_to 'Back', variances_path, class: 'btn btn-mini btn-warning'%>

app/views/variances/index.html.erb
<h2>Import variance data </h2>
<%= form_tag import_variances_path, multipart: true do %>
  <span class="btn btn-large btn-warning btn-file">
  <%= file_field_tag :file %>
  </span>
  <%= submit_tag "Upload location data", class: 'btn btn-mini btn-success' %>
<% end %> </br>

<%= link_to "CLEAR VARIANCE DATA", cleardata_variances_path, :method => :delete, class: 'btn btn-mini btn-danger' %> |
<%= link_to 'ADD NEW RECORD', new_variance_path, class: 'btn btn-mini btn-success' %>

<h1>Variance data</h1>

<div class="media">
<div class="media-body">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Barcode</th>
      <th>Location</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variances.each do |variance| %>
      <tr>
        <td><%= variance.BARCODE %></td>
        <td><%= variance.LOCATION %></td>
        <td><%= variance.QUANTITY %></td>
        <td><%= link_to 'Show', variance , class: 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'Edit', edit_variance_path(variance), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', variance, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>

<%= will_paginate @locations, renderer: BootstrapPagination::Rails  %>

app/views/variances/new.html.erb
<h1>New Variance</h1>

<%= render 'form', variance: @variance %>

<%= link_to 'Back', variances_path , class: 'btn btn-mini btn-warning'%>

app/views/variances/show.html.erb
<div class="container" style="margin-top: 30px">
<div class="card">
  <div class="card-header bg-success"><h2>Location details</h2></div>
  <div class="card-body">
<p id="notice"><%= notice %></p>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Barcode:</h4></div>
<div class="col-sm-10"><h4><%= @variance.BARCODE %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Location:</h4></div>
<div class="col-sm-10"><h4><%= @variance.LOCATION %> </h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Quantity:</h4></div>
<div class="col-sm-10"><h4><%= @variance.QUANTITY %></h4></div>
</div>

<%= link_to 'Edit', edit_variance_path(@variance), class: 'btn btn-mini btn-success' %> |
<%= link_to 'Back', variances_path, class: 'btn btn-mini btn-warning' %>