config/routes.rb
Rails.application.routes.draw do
  
  resources :variances do
    collection do
      post :import
      delete :cleardata
    end
  end
      
  resources :locations do
    collection do
      post :import
      delete :cleardata
      post :businessunit
    end
  end
  
  match '/business-form', to: 'home#business_form', via: [:get, :post]

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#home'
  resources :masters do
    collection do
      post :import
      delete :cleardata
      get :search
      get :prepare_import
    end  
  end
  
  namespace :api do
    resources :files, only: %i(index) do
      collection do
        get :download_db
        post :upload_csv
        get :verify_upload
      end
    end
  end

end

app/models/location.rb
class Location < ApplicationRecord
    require 'CSV'
    def self.import(file)
        h = CSV.open(file, headers: :first_row).map do |row| 
            row.to_h.merge!(created_at: DateTime.now, updated_at: DateTime.now)
        end
        Location.insert_all!(h)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all.paginate(page: params[:page], per_page: 100)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def businessunit
    Location.all.update_all(businessunit:params[:businessunit])
    flash[:notice] = "saved the business unit"
    redirect_to locations_path
  end 

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Location.import(params[:file])
    redirect_to locations_path, notice: "Location data added successfully !!"
  end 

  def cleardata
    # ActiveRecord::Base.connection.execute("DELETE FROM masters")
    Location.connection.truncate(Location.table_name)
    redirect_to locations_path
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:location, :zone, :type, :dept, :subdept)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="margin-top: 30px">
  <div class="card">
  <div class="card-body">

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :location, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :location ,class: "form-control"%></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :zone , class: "col-form-label"%></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :zone ,class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :name, class: "col-form-label" %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :name, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :dept, class: "col-form-label"  %></h4></div><br />
  <div class="col-sm-10"><h4><%= form.text_field :dept, class: "form-control" %></h4></div>
  </div>

  <div class="form-group row">
  <div class="col-sm-2"><h4><%= form.label :subdept, class: "col-form-label" %></h4></div><br />
    <div class="col-sm-10"><h4><%= form.text_field :subdept, class: "form-control" %></h4></div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location, class: 'btn btn-mini btn-success' %> |
<%= link_to 'Back', locations_path, class: 'btn btn-mini btn-warning' %>

app/views/locations/index.html.erb
<h2>Import location data </h2>
<%= form_tag import_locations_path, multipart: true do %>
  <span class="btn btn-large btn-warning btn-file">
  <%= file_field_tag :file %>
  </span>
  <%= submit_tag "Upload location data", class: 'btn btn-mini btn-success' %>
<% end %> </br>

<%= link_to "CLEAR LOCATION DATA", cleardata_locations_path, :method => :delete, class: 'btn btn-mini btn-danger' %> |
<%= link_to 'ADD NEW RECORD', new_location_path, class: 'btn btn-mini btn-success' %> <br /><br />

<h1>Location data</h1>

<div class="media">
<div class="media-body">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Location</th>
      <th>Zone</th>
      <th>Name</th>
      <th>Dept</th>
      <th>Subdept</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.location %></td>
        <td><%= location.zone %></td>
        <td><%= location.name %></td>
        <td><%= location.dept %></td>
        <td><%= location.subdept %></td>
        <td><%= link_to 'Show', location, class: 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'Edit', edit_location_path(location), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', location, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%= will_paginate @locations, renderer: BootstrapPagination::Rails  %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path , class: 'btn btn-mini btn-warning'%>

app/views/locations/show.html.erb
<div class="container" style="margin-top: 30px">
<div class="card">
  <div class="card-header bg-success"><h2>Location details</h2></div>
  <div class="card-body">
<p id="notice"><%= notice %></p>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Location:</h4></div>
<div class="col-sm-10"><h4><%= @location.location %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Zone:</h4></div>
<div class="col-sm-10"><h4><%= @location.zone %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Name:</h4></div>
<div class="col-sm-10"><h4><%= @location.name %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Dept:</h4></div>
<div class="col-sm-10"><h4><%= @location.dept %></h4></div>
</div>

<div class="form-group row">
<div class="col-sm-2 col-form-label"><h4>Subdept:</h4></div>
<div class="col-sm-10"><h4><%= @location.subdept %></h4></div>
</p>

<%= link_to 'Edit', edit_location_path(@location), class: 'btn btn-mini btn-success' %> |
<%= link_to 'Back', locations_path, class: 'btn btn-mini btn-warning' %>