config/routes.rb
Rails.application.routes.draw do
  
  resources :variances do
    collection do
      post :import
      delete :cleardata
    end
  end
      
  resources :locations do
    collection do
      post :import
      delete :cleardata
      post :businessunit
    end
  end
  
  match '/business-form', to: 'home#business_form', via: [:get, :post]

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#home'
  resources :masters do
    collection do
      post :import
      delete :cleardata
      get :search
      get :prepare_import
    end  
  end
  
  namespace :api do
    resources :files, only: %i(index) do
      collection do
        get :download_db
        post :upload_csv
        get :verify_upload
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PST</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>



  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-info">
  <a class="navbar-brand" href="/">PST</a>

  <div class="conatiner">
    <ul class="nav nav-tabs">
  <% if current_user %>
            <li><%= link_to 'Dashboard', masters_path %> </li>
            <li><%= link_to 'Master data', masters_path %> </li>
            <li><%= link_to 'Location data', locations_path %> </li>
            <li><%= link_to 'Variance data', variances_path %> </li>
            <li><%= link_to 'Count report', masters_path %> </li>
            <li><%= link_to 'Variance report', masters_path %> </li>
            <li><%= link_to 'Upload data', masters_path %> </li>
            <li><%= link_to 'Edit User', edit_user_registration_path, class: "btn btn-info btn-small navbar-btn", style:"margin-right: 5px;" %> </li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-danger btn-small navbar-btn", style:"margin-right: 5px;" %> </li>
        <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path, class: "btn btn-warning btn-small navbar-btn", style:"margin-right: 5px;" %> </li>
            <li><%= link_to 'Sign in', new_user_session_path, class: "btn btn-success btn-small navbar-btn" %> </li>
        <% end %>
      </ul>  
      </div>
      </nav>


    <% if flash[:notice] %>
      <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error">
         <button type="button" class="close" data-dismiss="alert">&times;></button>
         <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
       <div class="alert">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
    <% end %>   
       
    <%= yield %>
    </div>
  </body>
</html>